# Generated by Django 4.2.7 on 2023-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='furniture',
            name='material',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
